/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 amazonlogo.gltf --transform 
Files: amazonlogo.gltf [32.6KB] > amazonlogo-transformed.glb [21.74KB] (33%)
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/amazon-logo-947dc2222ea74a75b3ba640f6653caba
Title: Amazon Logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/amazonlogo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Amazon_Logo_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-5.394, -112.815, 0]} scale={[1, 1, 2.152]} />
    </group>
  )
}

useGLTF.preload('/amazonlogo-transformed.glb')
