/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 docker.gltf --transform 
Files: docker.gltf [78.31KB] > docker-transformed.glb [44.02KB] (44%)
Author: Maurice Svay (https://sketchfab.com/mauricesvay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moby-dock-docker-whale-b706010291ca46ad8daca2d4aeb79edd
Title: Moby Dock (Docker whale)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/docker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_0.geometry} material={materials.crate} position={[-0.754, -0.035, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.331} />
      <mesh geometry={nodes.Sphere001_0.geometry} material={materials.whale_outline} position={[-0.754, -0.035, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.331} />
      <instancedMesh args={[nodes.Cube_0.geometry, materials.crate, 13]} instanceMatrix={nodes.Cube_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/docker-transformed.glb')
