/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 endlessloop.gltf --transform 
Files: endlessloop.gltf [4.83MB] > endlessloop-transformed.glb [3.4MB] (29%)
Author: Marcel van Duijn (https://sketchfab.com/MarcelvanDuijn)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/neonroad-endless-loop-425480c926144a3395b9cc8f672a8db4
Title: NeonRoad endless loop
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/endlessloop-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.004}>
          <group name="Moving" position={[0, 0, 3966.667]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="Enviroment" scale={[13, 30, 13.98]}>
              <mesh name="Enviroment_Material001_0" geometry={nodes.Enviroment_Material001_0.geometry} material={materials.PaletteMaterial001} />
              <mesh name="Enviroment_Material002_0" geometry={nodes.Enviroment_Material002_0.geometry} material={materials.PaletteMaterial002} />
            </group>
            <group name="PalmTree_Left" position={[-7.713, 0, 0]} scale={0.6}>
              <group name="PalmTreeTopLeft" position={[1.944, 0, 14.65]} scale={0.572}>
                <mesh name="PalmTreeTopLeft_Material_0" geometry={nodes.PalmTreeTopLeft_Material_0.geometry} material={materials.PaletteMaterial003} />
                <mesh name="PalmTreeTopLeft_Material008_0" geometry={nodes.PalmTreeTopLeft_Material008_0.geometry} material={materials.PaletteMaterial002} />
              </group>
              <mesh name="PalmTree_Left_Material009_0" geometry={nodes.PalmTree_Left_Material009_0.geometry} material={materials.PaletteMaterial003} />
              <mesh name="PalmTree_Left_Material010_0" geometry={nodes.PalmTree_Left_Material010_0.geometry} material={materials.PaletteMaterial002} />
            </group>
            <group name="Road" position={[0, 0, 0.094]} scale={[2.977, 30, 2.977]}>
              <group name="CenterLine" position={[0, -0.005, 0.01]} scale={[0.026, 0.1, 0.062]}>
                <mesh name="CenterLine_Material007_0" geometry={nodes.CenterLine_Material007_0.geometry} material={materials.PaletteMaterial002} />
              </group>
              <group name="SideRight" position={[1.016, 0, 0.007]} rotation={[-Math.PI, 0, 0]} scale={[-0.016, -1, -1]}>
                <mesh name="SideRight_Material006_0" geometry={nodes.SideRight_Material006_0.geometry} material={materials.PaletteMaterial002} />
              </group>
              <group name="SideSideLeft" position={[-1.016, 0, 0.007]} rotation={[-Math.PI, 0, 0]} scale={[-0.016, -1, -1]}>
                <mesh name="SideSideLeft_Material006_0" geometry={nodes.SideSideLeft_Material006_0.geometry} material={materials.PaletteMaterial002} />
              </group>
              <mesh name="Road_Material005_0" geometry={nodes.Road_Material005_0.geometry} material={materials.PaletteMaterial003} />
            </group>
            <group name="PalmTree_Left001" position={[7.236, 0, 0]} scale={0.6}>
              <group name="PalmTreeTopLeft001" position={[1.944, 0, 14.65]} scale={0.572}>
                <mesh name="PalmTreeTopLeft001_Material_0" geometry={nodes.PalmTreeTopLeft001_Material_0.geometry} material={materials.PaletteMaterial003} />
                <mesh name="PalmTreeTopLeft001_Material008_0" geometry={nodes.PalmTreeTopLeft001_Material008_0.geometry} material={materials.PaletteMaterial002} />
              </group>
              <mesh name="PalmTree_Left001_Material009_0" geometry={nodes.PalmTree_Left001_Material009_0.geometry} material={materials.PaletteMaterial003} />
              <mesh name="PalmTree_Left001_Material010_0" geometry={nodes.PalmTree_Left001_Material010_0.geometry} material={materials.PaletteMaterial002} />
            </group>
          </group>
        </group>
        <mesh name="BackGround_Material004_0" geometry={nodes.BackGround_Material004_0.geometry} material={materials.PaletteMaterial003} position={[2.87, 7.877, -212.464]} rotation={[-Math.PI, 0, 0]} scale={[-210.118, 212.077, 36.401]} />
        <mesh name="Sun_Material003_0" geometry={nodes.Sun_Material003_0.geometry} material={materials.PaletteMaterial002} position={[0.437, 0, -189.322]} rotation={[-Math.PI / 2, 0, 0]} scale={15.102} />
      </group>
    </group>
  )
}

useGLTF.preload('/endlessloop-transformed.glb')
