/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 model4.gltf --transform 
Files: model4.gltf [7.94MB] > model4-transformed.glb [186.62KB] (98%)
Author: Nihkolic (https://sketchfab.com/nihkolic)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/midways-1980-pac-man-arcade-machine-2b7e202269124dc8ad1f0fac72e8fb17
Title: Midway's 1980 Pac-Man Arcade Machine
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model4-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arcade_sideL_low_arcade_MAT_0.geometry} material={materials.arcade_MAT} scale={0.062} />
    </group>
  )
}

useGLTF.preload('/model4-transformed.glb')
